/*
EX:
SELECT 
PKUDF_ROC_DT_FNUMBER('991111','')
*/


DROP FUNCTION IF EXISTS FWJDBA.PKUDF_ROC_DT_FNUMBER;
CREATE FUNCTION FWJDBA.`PKUDF_ROC_DT_FNUMBER`(  P_DATE VARCHAR(50),P_TYPE CHAR(1) ) RETURNS  VARCHAR(50) CHARSET UTF8
    DETERMINISTIC
    COMMENT '數字轉民國日期'
BEGIN
  DECLARE ROC_DT VARCHAR(50);
  DECLARE ROC_Y CHAR(4);
  DECLARE ROC_MM CHAR(2);
  DECLARE ROC_DD CHAR(2);
  -- 設定參數初始直
  SET ROC_DT = '';
  SET P_DATE =  REPLACE(REPLACE(REPLACE(P_DATE,'-',''),'/',''),'.','');
  -- 切割年月日
  IF LENGTH(P_DATE)=8 THEN
  -- 20180101
    SET ROC_Y = SUBSTR(P_DATE,1,4)-1911;
    SET ROC_MM = SUBSTR(P_DATE,5,2);
    SET ROC_DD = SUBSTR(P_DATE,7,2);
  ELSEIF LENGTH(P_DATE)=7 THEN
  -- 1070101
    SET ROC_Y = SUBSTR(P_DATE,1,3);
    SET ROC_MM = SUBSTR(P_DATE,4,2);
    SET ROC_DD = SUBSTR(P_DATE,6,2);
    
  ELSEIF LENGTH(P_DATE)=6 THEN
  -- 990101
    SET ROC_Y = SUBSTR(P_DATE,1,2);
    SET ROC_MM = SUBSTR(P_DATE,3,2);
    SET ROC_DD = SUBSTR(P_DATE,5,2);
  ELSE
    SET ROC_DT = '請輸入正確格式';
  END IF;
  -- 資料驗證
  IF ROC_MM > 12 THEN
    SET ROC_DT = '月份錯誤';
  ELSEIF ROC_DD > 31 THEN
    SET ROC_DT = '日期錯誤';
  END IF;
  IF ROC_DT = '' THEN
    IF P_TYPE = 'C' THEN
      SET ROC_DT = CONCAT('中華民國',ROC_Y,'年',ROC_MM,'月',ROC_DD,'日');
    ELSE
      SET ROC_DT =  CONCAT(ROC_Y,P_TYPE,ROC_MM,P_TYPE,ROC_DD);
    END IF;
  END IF;
  RETURN ROC_DT;
END;