/*EX:SELECT PKUDF_ROC_DT(current_date,'C')*/


DROP FUNCTION IF EXISTS fwjdba.PKUDF_ROC_DT;
CREATE FUNCTION fwjdba.`PKUDF_ROC_DT`( P_DATE  DATE,P_TYPE CHAR(1) ) RETURNS varchar(50) CHARSET  utf8
    DETERMINISTIC
    COMMENT '西元轉民國日期'
BEGIN
DECLARE ROC_DT VARCHAR(50);
DECLARE ROC_Y CHAR(3);
DECLARE ROC_MD CHAR(5);
IF P_TYPE = 'C' THEN
  SET ROC_DT = CONCAT('中華民國',CAST(YEAR(P_DATE)-1911 AS CHAR(3)),'年',CAST(DATE_FORMAT(P_DATE,'%m月%d日') AS CHAR(10)));
ELSE
  SET ROC_DT =  CONCAT(YEAR(P_DATE)-1911,P_TYPE,month(P_DATE),P_TYPE,day(P_DATE));
END IF;
RETURN ROC_DT;
END;